// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package accrual is a generated GoMock package.
package accrual

import (
	reflect "reflect"

	dto "github.com/egor-zakharov/go-musthave-diploma-tpl/internal/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// SendOrder mocks base method.
func (m *MockClient) SendOrder(orderID string) (*dto.AccrualOrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendOrder", orderID)
	ret0, _ := ret[0].(*dto.AccrualOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendOrder indicates an expected call of SendOrder.
func (mr *MockClientMockRecorder) SendOrder(orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendOrder", reflect.TypeOf((*MockClient)(nil).SendOrder), orderID)
}
